export interface StudentListModelplusclassid {
            id:string,
  studentId: string, 
  classId: string, 
  yearId: string, 
  addDate: string, 
  addedBy: string, 
  studentName: string, 
  studentddress: string,
  studentdateofbirth: string,
}
export interface StudentListModel {
          id  :string,
          fName  :string,
  lName: string,
  fullName: string,
          midName  :string,
          email  :string,
          phone  :string,
          address  :string,
          birthDate  :string,
          gender  :string,
          fGuardianName  :string,
          fGuardianPhone  :string,
          fGuardianEmail  :string,
          fGuardianAddress  :string,
          fGuardianRelation  :string,
          sGuardianName  :string,
          sGuardianPhone  :string,
          sGuardianEmail  :string,
          sGuardianAddress  :string,
          sGuardianRelation  :string,
          medicalReport  :string,
          bloodGroup  :string,
          userId  :string,
          addedBy  :string,
          addedTime  :string, 
}
export interface StudentAddModel {
          fName  :string,
          lName  :string,
  midName: string,

          email: string,
          phone  :string,
          address  :string,
          birthDate  :Date,
          gender  :string,
          fGuardianName  :string,
          fGuardianPhone  :string,
          fGuardianEmail  :string,
          fGuardianAddress  :string,
          fGuardianRelation  :string,
          sGuardianName  :string,
          sGuardianPhone  :string,
          sGuardianEmail  :string,
          sGuardianAddress  :string,
          sGuardianRelation  :string,
          medicalReport  :string,
          bloodGroup  :string,
          userId  :string,
          addedBy  :string,
          addedTime  :Date, 
}
export interface StudentUpdModel {
          fName  :string,
          lName  :string,
          midName  :string,
          email  :string,
          phone  :string,
          address  :string,
          birthDate  :Date,
          gender  :string,
          fGuardianName  :string,
          fGuardianPhone  :string,
          fGuardianEmail  :string,
          fGuardianAddress  :string,
          fGuardianRelation  :string,
          sGuardianName  :string,
          sGuardianPhone  :string,
          sGuardianEmail  :string,
          sGuardianAddress  :string,
          sGuardianRelation  :string,
          medicalReport  :string,
          bloodGroup  :string,
          userId  :string,
          addedBy  :string,
          addedTime  :Date, 
}

export interface StudentUpdToCompleteModel {
   midName :  string ,
   phone :  string ,
   address :  string ,
   birthDate :  Date ,
   gender :  string ,
   fGuardianName :  string ,
   fGuardianPhone :  string ,
   fGuardianEmail :  string ,
   fGuardianAddress :  string ,
   fGuardianRelation :  string ,
   sGuardianName :  string ,
   sGuardianPhone :  string ,
   sGuardianEmail :  string ,
   sGuardianAddress :  string ,
   sGuardianRelation :  string ,
   medicalReport :  string ,
   bloodGroup :  string ,
   addedBy :  string ,
  bid: string,
  classIds: string[],
  chronicDiseaseIds: string[],
  yearId:string
}

export interface StudentsByClassIdYearIdModel {
  yearId: string,
  studentIds: string[],
  ClassGId: string,
AddedBy:string
}
export interface GetRequest {
  yearId: string
  classId: string
}
